export const GET_STUDENTS = "GET_STUDENTS";
export const GET_ONE_STUDENT = "GET_ONE_STUDENT";


export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const STUDENTS_LOADING = "STUDENTS_LOADING";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'; 